const home=document.querySelector('#home'),game=document.querySelector('#game'),canvas=document.querySelector('#gameCanvas');const ctx=canvas.getContext('2d');const keys=new Set();let running=false,last=0,elapsed=0,score=0,health=100,ammo=30,aim=false;const player={x:0,y:0,angle:0,speed:180};const bots=[{x:420,y:280,hp:100,alive:true},{x:720,y:450,hp:100,alive:true},{x:980,y:260,hp:100,alive:true}];
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();
function setText(id,v){document.querySelector(id).textContent=v}function start(){home.classList.add('hidden');game.classList.remove('hidden');running=true;elapsed=0;health=100;ammo=30;score=0;player.x=600;player.y=400;document.querySelector('#message').textContent='CLICK THE VIEWPORT TO CAPTURE MOUSE';canvas.focus();requestAnimationFrame(loop)}
function exit(){running=false;document.exitPointerLock?.();game.classList.add('hidden');home.classList.remove('hidden')}
document.querySelector('#playBtn').onclick=start;document.querySelector('#exitBtn').onclick=exit;document.querySelector('#howBtn').onclick=()=>document.querySelector('#helpDialog').showModal();document.querySelector('#closeHelp').onclick=()=>document.querySelector('#helpDialog').close();
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='r')ammo=30});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('click',()=>{canvas.requestPointerLock?.();document.querySelector('#message').textContent='WASD TO MOVE · LMB TO FIRE'});addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)player.angle+=e.movementX*.002*(aim?.65:1)});addEventListener('mousedown',e=>{if(e.button===2){aim=true;e.preventDefault()}if(e.button===0&&running)shoot()});addEventListener('mouseup',e=>{if(e.button===2)aim=false});addEventListener('contextmenu',e=>e.preventDefault());
function shoot(){if(ammo<=0)return;ammo--;let best=null,bd=Infinity;for(const b of bots){if(!b.alive)continue;const dx=b.x-player.x,dy=b.y-player.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx),diff=Math.abs(Math.atan2(Math.sin(a-player.angle),Math.cos(a-player.angle)));if(diff<.09&&d<850&&d<bd){best=b;bd=d}}if(best){best.hp-=34;if(best.hp<=0){best.alive=false;score++;setTimeout(()=>{best.hp=100;best.alive=true;best.x=100+Math.random()*1000;best.y=150+Math.random()*500},1800)}}}
function update(dt){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;const l=Math.hypot(dx,dy)||1;const speed=keys.has('shift')?player.speed*1.55:player.speed;player.x=Math.max(40,Math.min(1160,player.x+dx/l*speed*dt));player.y=Math.max(120,Math.min(680,player.y+dy/l*speed*dt));for(const b of bots){if(!b.alive)continue;const d=Math.hypot(player.x-b.x,player.y-b.y);if(d<550){b.x+=(player.x-b.x)/Math.max(d,1)*25*dt;b.y+=(player.y-b.y)/Math.max(d,1)*25*dt;if(d<280&&Math.random()<dt*.35)health=Math.max(0,health-5)}}elapsed+=dt;if(elapsed>=600){running=false;document.querySelector('#message').textContent='MATCH COMPLETE — SCORE '+score}}
function worldToScreen(x,y){return{x:x-player.x+canvas.width/2,y:y-player.y+canvas.height/2}}
function draw(){ctx.fillStyle='#111820';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(canvas.width/2-player.x,canvas.height/2-player.y);ctx.fillStyle='#1b2832';ctx.fillRect(0,0,1200,800);ctx.strokeStyle='#334554';ctx.lineWidth=4;ctx.strokeRect(25,95,1150,620);for(let x=80;x<1160;x+=80){ctx.strokeStyle='#22323e';ctx.beginPath();ctx.moveTo(x,120);ctx.lineTo(x,690);ctx.stroke()}for(let y=150;y<700;y+=80){ctx.strokeStyle='#22323e';ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(1160,y);ctx.stroke()}ctx.fillStyle='#303d48';for(const r of [[180,180,150,70],[760,170,180,80],[360,520,180,65],[850,500,160,70]])ctx.fillRect(...r);for(const b of bots){if(!b.alive)continue;ctx.fillStyle='#b95d67';ctx.beginPath();ctx.arc(b.x,b.y,20,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20252b';ctx.fillRect(b.x-24,b.y-34,48,5);ctx.fillStyle='#79f2b0';ctx.fillRect(b.x-24,b.y-34,48*b.hp/100,5)}ctx.fillStyle='#d9e2ea';ctx.beginPath();ctx.arc(player.x,player.y,16,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d9e2ea';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(player.x,player.y);ctx.lineTo(player.x+Math.cos(player.angle)*35,player.y+Math.sin(player.angle)*35);ctx.stroke();ctx.restore();setText('#health',health);setText('#ammo',ammo);setText('#score',score);setText('#time',new Date(Math.max(0,600-elapsed)*1000).toISOString().slice(14,19))}
function loop(t){if(!running)return;const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
